# Generated by Django 6.0.8 on 2026-09-26 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Non-sensitive title used for organization and fast indexing.', max_length=200)),
                ('encrypted_content', models.TextField(help_text='Ciphertext encrypted at the application layer via Fernet before database storage.')),
                ('category', models.CharField(choices=[('Personal', 'Personal'), ('Study', 'Study'), ('Work', 'Work'), ('Ideas', 'Ideas'), ('Journal', 'Journal')], default='Personal', help_text='Category classification for organizing notes.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the note was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the note was last updated.')),
                ('owner', models.ForeignKey(help_text='User who owns and has exclusive access to this note.', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
